### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by EndRollModel** [EndRollModel/Holo_DD_Notify#1]
feat : 
- [ ] revoke notify token / 解除綁定去除notify token 

bug :
- [ ] connect twitter stream some time will disconnect or error /  連線推特時 流容易產生錯誤
error msg : "This stream is currently at the maximum allowed connection limit." 

issue : 
- [ ] bot flow & gui change / 機器人操作流程與畫面更新
- [x] sub page have a button can do all check or all check cancel / 訂閱頁面增加全勾選或是全取消
- [ ] url change to liff / 網址更換為liff
- [ ] can review tweets info (switch) / 可以瀏覽該則推文的詳細資訊 ( 做成開關 )

new feat :
- [ ] youtube stream notify / yt直播提醒
