### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by EndRollModel** [EndRollModel/Holo_DD_Notify#1]
feat : 

bug :

maybe : 
- [ ] count tweets data / 統計所有內容 做成資料
- [ ] add data write on google sheet / 寫入資料的方式新增在google sheet 上
- [ ] select page style change / 改變選擇通知對象的網頁內容

late : 
- [ ] line bot bind max set 100 / 設定機器人綁定數量為100 為防止過大讀取

completed :
- [x] change module node-fetch to axios / 更換notify使用套件node-fetch為axios
- [x] change some holomem image / 更替某些選擇的頭像圖片
- [x] add id 3th / 新增ID三期生
- [x] add hololiveX / 新增六期生
- [x] some times start process twitter request fail / 啟動時有機率不會啟動推特請求 
- [x] axios error (axios no response) reconnect / axios 若無法進行請求後 則會斷開連線 設定重新連線
- [x] add en 2 gen, singer, id, id 2 gen list / 新增en2期, singer, id, id 2期名單
- [x] bot flow & ui change / 機器人操作流程與畫面更新 
- [x] sub page have a button can do all check or all check cancel / 訂閱頁面增加全勾選或是全取消
- [x] url change to liff / 網址更換為liff
- [x] can review tweets info (switch) / 可以瀏覽該則推文的詳細資訊 ( 做成開關 )
- [x] mute button / 靜音設定開關 
- [x] revoke notify token / 解除綁定去除notify token 
- [x] reconnect / 重連線機制
- [x] connect twitter stream some time will disconnect or error /  連線推特時 流容易產生錯誤
error msg : "This stream is currently at the maximum allowed connection limit." 
平均一天會斷線一次 甚至於半天內就會斷線
- [x] down firebase loading / 減少重複讀取firebase資料庫的機制 (持續讀取對於Firebase有點龐大)

observed:
- [x] twitter api time out loop / 推特api持續連線中斷 (21/05/12開始) 
now : [問題來源](https://twittercommunity.com/t/curl-18-transfer-closed-with-outstanding-read-data-remaining-at-api-v2/154069/2) & [問題](https://twittercommunity.com/t/filtered-stream-disconnects-every-5-minutes-on-nodejs/153866/7) 
修正後重連機制後極低機率發生
- [x] line notify ETIMEDOUT & ENETUNREACH / LineNotify發生錯誤 (極低機率發生)
- [x] notify send fail / notify傳送錯誤時 發送功能會失效 (推估是ip更換 將套件由node-fetch 換到 axios 測試)

---

**Comment by aaronlin0122** [comment]
請問大佬有 Discord 嗎 :3

**Comment by EndRollModel** [comment]
> 請問大佬有 Discord 嗎 :3

抱歉 晚回覆了 我已經加你好友了 請不要叫我大佬 :3
